version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    restart: unless-stopped
    command:
      - --config.my-cnf=/cfg/.my.cnf
      - --mysqld.address=172.17.0.1:3306
    environment:
      DATA_SOURCE_NAME: root:root@(mysql:3306)/db # Utilisation de root
    ports:
      - "9104:9104"
    volumes:
      - "./.my.cnf:/cfg/.my.cnf"
    depends_on:
      - mysql

  springboot_app:
    image: firasprojet/tpfoyer:1.0.0
    depends_on:
      - mysql
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    ports:
      - "8089:8089"

volumes:
  mysql_data:
